// flow-typed signature: 5e5a3a48c30fcacaa34014e2c07cfd9a
// flow-typed version: <<STUB>>/jStat_v^1.7.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jStat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jStat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jStat/build/doctool' {
  declare module.exports: any;
}

declare module 'jStat/build/lib/markdown' {
  declare module.exports: any;
}

declare module 'jStat/dist/jstat' {
  declare module.exports: any;
}

declare module 'jStat/dist/jstat.min' {
  declare module.exports: any;
}

declare module 'jStat/doc/assets/sh_javascript.min' {
  declare module.exports: any;
}

declare module 'jStat/doc/assets/sh_main' {
  declare module.exports: any;
}

declare module 'jStat/src/_footer' {
  declare module.exports: any;
}

declare module 'jStat/src/_header' {
  declare module.exports: any;
}

declare module 'jStat/src/core' {
  declare module.exports: any;
}

declare module 'jStat/src/distribution' {
  declare module.exports: any;
}

declare module 'jStat/src/linearalgebra' {
  declare module.exports: any;
}

declare module 'jStat/src/models' {
  declare module.exports: any;
}

declare module 'jStat/src/regression' {
  declare module.exports: any;
}

declare module 'jStat/src/special' {
  declare module.exports: any;
}

declare module 'jStat/src/test' {
  declare module.exports: any;
}

declare module 'jStat/src/vector' {
  declare module.exports: any;
}

declare module 'jStat/test/core/alter-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/antidiag-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/arange-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/clear-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/col-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/cols-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/copy-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/create-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/diag-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/diagonal-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/dimensions-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/extend-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/identity-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/jstat-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/map-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/ones-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/rand-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/row-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/rows-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/seq-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/slice-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/sliceAssign-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/symmetric-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/transpose-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/utils-test' {
  declare module.exports: any;
}

declare module 'jStat/test/core/zeros-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/arcsine-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/beta-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/binomial-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/cauchy-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/central-f-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/chisquare-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/gamma-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/hypergeometric-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/inverse-gamma-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/kumaraswamy-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/laplace-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/lognormal-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/neg-bin-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/noncentralt-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/normal-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/pareto-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/poisson-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/student-t-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/triangular-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/tukey-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/uniform-test' {
  declare module.exports: any;
}

declare module 'jStat/test/distribution/weibull-test' {
  declare module.exports: any;
}

declare module 'jStat/test/env' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/abs-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/add-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/angle-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/aug-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/cholesky-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/det-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/divide-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/dot-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/exp-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/gauss-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/inv-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/log-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/lstsq-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/lu-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/multiply-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/norm-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/outer-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/pow-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/qr-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/subtract-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/triaLowSolve-test' {
  declare module.exports: any;
}

declare module 'jStat/test/linearalgebra/triaUpSolve-test' {
  declare module.exports: any;
}

declare module 'jStat/test/models/R2-test' {
  declare module.exports: any;
}

declare module 'jStat/test/models/simple-regression-test' {
  declare module.exports: any;
}

declare module 'jStat/test/models/thousand-size-test' {
  declare module.exports: any;
}

declare module 'jStat/test/special/gammafn-test' {
  declare module.exports: any;
}

declare module 'jStat/test/special/gammap-test' {
  declare module.exports: any;
}

declare module 'jStat/test/special/lowRegGamma-test' {
  declare module.exports: any;
}

declare module 'jStat/test/template' {
  declare module.exports: any;
}

declare module 'jStat/test/test/differenceOfProportions-test' {
  declare module.exports: any;
}

declare module 'jStat/test/test/qtest-test' {
  declare module.exports: any;
}

declare module 'jStat/test/test/ztest-test' {
  declare module.exports: any;
}

declare module 'jStat/test/umd/commonjs-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/coeffvar-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/corrcoeff-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/covariance-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/cumprod-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/cumsum-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/deviation-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/diff-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/geomean-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/histogram-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/kurtosis-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/max-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/mean-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/meandev-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/meansqerr-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/meddev-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/median-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/min-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/mode-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/percentile-of-score-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/percentile-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/product-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/quantiles-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/quartiles-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/range-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/rank-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/skewness-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/spearman-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/stdev-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/sum-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/sumrow-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/sumsqerr-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/sumsqrd-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/unique-test' {
  declare module.exports: any;
}

declare module 'jStat/test/vector/variance-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jStat/build/doctool.js' {
  declare module.exports: $Exports<'jStat/build/doctool'>;
}
declare module 'jStat/build/lib/markdown.js' {
  declare module.exports: $Exports<'jStat/build/lib/markdown'>;
}
declare module 'jStat/dist/jstat.js' {
  declare module.exports: $Exports<'jStat/dist/jstat'>;
}
declare module 'jStat/dist/jstat.min.js' {
  declare module.exports: $Exports<'jStat/dist/jstat.min'>;
}
declare module 'jStat/doc/assets/sh_javascript.min.js' {
  declare module.exports: $Exports<'jStat/doc/assets/sh_javascript.min'>;
}
declare module 'jStat/doc/assets/sh_main.js' {
  declare module.exports: $Exports<'jStat/doc/assets/sh_main'>;
}
declare module 'jStat/src/_footer.js' {
  declare module.exports: $Exports<'jStat/src/_footer'>;
}
declare module 'jStat/src/_header.js' {
  declare module.exports: $Exports<'jStat/src/_header'>;
}
declare module 'jStat/src/core.js' {
  declare module.exports: $Exports<'jStat/src/core'>;
}
declare module 'jStat/src/distribution.js' {
  declare module.exports: $Exports<'jStat/src/distribution'>;
}
declare module 'jStat/src/linearalgebra.js' {
  declare module.exports: $Exports<'jStat/src/linearalgebra'>;
}
declare module 'jStat/src/models.js' {
  declare module.exports: $Exports<'jStat/src/models'>;
}
declare module 'jStat/src/regression.js' {
  declare module.exports: $Exports<'jStat/src/regression'>;
}
declare module 'jStat/src/special.js' {
  declare module.exports: $Exports<'jStat/src/special'>;
}
declare module 'jStat/src/test.js' {
  declare module.exports: $Exports<'jStat/src/test'>;
}
declare module 'jStat/src/vector.js' {
  declare module.exports: $Exports<'jStat/src/vector'>;
}
declare module 'jStat/test/core/alter-test.js' {
  declare module.exports: $Exports<'jStat/test/core/alter-test'>;
}
declare module 'jStat/test/core/antidiag-test.js' {
  declare module.exports: $Exports<'jStat/test/core/antidiag-test'>;
}
declare module 'jStat/test/core/arange-test.js' {
  declare module.exports: $Exports<'jStat/test/core/arange-test'>;
}
declare module 'jStat/test/core/clear-test.js' {
  declare module.exports: $Exports<'jStat/test/core/clear-test'>;
}
declare module 'jStat/test/core/col-test.js' {
  declare module.exports: $Exports<'jStat/test/core/col-test'>;
}
declare module 'jStat/test/core/cols-test.js' {
  declare module.exports: $Exports<'jStat/test/core/cols-test'>;
}
declare module 'jStat/test/core/copy-test.js' {
  declare module.exports: $Exports<'jStat/test/core/copy-test'>;
}
declare module 'jStat/test/core/create-test.js' {
  declare module.exports: $Exports<'jStat/test/core/create-test'>;
}
declare module 'jStat/test/core/diag-test.js' {
  declare module.exports: $Exports<'jStat/test/core/diag-test'>;
}
declare module 'jStat/test/core/diagonal-test.js' {
  declare module.exports: $Exports<'jStat/test/core/diagonal-test'>;
}
declare module 'jStat/test/core/dimensions-test.js' {
  declare module.exports: $Exports<'jStat/test/core/dimensions-test'>;
}
declare module 'jStat/test/core/extend-test.js' {
  declare module.exports: $Exports<'jStat/test/core/extend-test'>;
}
declare module 'jStat/test/core/identity-test.js' {
  declare module.exports: $Exports<'jStat/test/core/identity-test'>;
}
declare module 'jStat/test/core/jstat-test.js' {
  declare module.exports: $Exports<'jStat/test/core/jstat-test'>;
}
declare module 'jStat/test/core/map-test.js' {
  declare module.exports: $Exports<'jStat/test/core/map-test'>;
}
declare module 'jStat/test/core/ones-test.js' {
  declare module.exports: $Exports<'jStat/test/core/ones-test'>;
}
declare module 'jStat/test/core/rand-test.js' {
  declare module.exports: $Exports<'jStat/test/core/rand-test'>;
}
declare module 'jStat/test/core/row-test.js' {
  declare module.exports: $Exports<'jStat/test/core/row-test'>;
}
declare module 'jStat/test/core/rows-test.js' {
  declare module.exports: $Exports<'jStat/test/core/rows-test'>;
}
declare module 'jStat/test/core/seq-test.js' {
  declare module.exports: $Exports<'jStat/test/core/seq-test'>;
}
declare module 'jStat/test/core/slice-test.js' {
  declare module.exports: $Exports<'jStat/test/core/slice-test'>;
}
declare module 'jStat/test/core/sliceAssign-test.js' {
  declare module.exports: $Exports<'jStat/test/core/sliceAssign-test'>;
}
declare module 'jStat/test/core/symmetric-test.js' {
  declare module.exports: $Exports<'jStat/test/core/symmetric-test'>;
}
declare module 'jStat/test/core/transpose-test.js' {
  declare module.exports: $Exports<'jStat/test/core/transpose-test'>;
}
declare module 'jStat/test/core/utils-test.js' {
  declare module.exports: $Exports<'jStat/test/core/utils-test'>;
}
declare module 'jStat/test/core/zeros-test.js' {
  declare module.exports: $Exports<'jStat/test/core/zeros-test'>;
}
declare module 'jStat/test/distribution/arcsine-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/arcsine-test'>;
}
declare module 'jStat/test/distribution/beta-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/beta-test'>;
}
declare module 'jStat/test/distribution/binomial-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/binomial-test'>;
}
declare module 'jStat/test/distribution/cauchy-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/cauchy-test'>;
}
declare module 'jStat/test/distribution/central-f-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/central-f-test'>;
}
declare module 'jStat/test/distribution/chisquare-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/chisquare-test'>;
}
declare module 'jStat/test/distribution/gamma-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/gamma-test'>;
}
declare module 'jStat/test/distribution/hypergeometric-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/hypergeometric-test'>;
}
declare module 'jStat/test/distribution/inverse-gamma-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/inverse-gamma-test'>;
}
declare module 'jStat/test/distribution/kumaraswamy-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/kumaraswamy-test'>;
}
declare module 'jStat/test/distribution/laplace-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/laplace-test'>;
}
declare module 'jStat/test/distribution/lognormal-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/lognormal-test'>;
}
declare module 'jStat/test/distribution/neg-bin-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/neg-bin-test'>;
}
declare module 'jStat/test/distribution/noncentralt-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/noncentralt-test'>;
}
declare module 'jStat/test/distribution/normal-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/normal-test'>;
}
declare module 'jStat/test/distribution/pareto-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/pareto-test'>;
}
declare module 'jStat/test/distribution/poisson-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/poisson-test'>;
}
declare module 'jStat/test/distribution/student-t-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/student-t-test'>;
}
declare module 'jStat/test/distribution/triangular-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/triangular-test'>;
}
declare module 'jStat/test/distribution/tukey-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/tukey-test'>;
}
declare module 'jStat/test/distribution/uniform-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/uniform-test'>;
}
declare module 'jStat/test/distribution/weibull-test.js' {
  declare module.exports: $Exports<'jStat/test/distribution/weibull-test'>;
}
declare module 'jStat/test/env.js' {
  declare module.exports: $Exports<'jStat/test/env'>;
}
declare module 'jStat/test/linearalgebra/abs-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/abs-test'>;
}
declare module 'jStat/test/linearalgebra/add-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/add-test'>;
}
declare module 'jStat/test/linearalgebra/angle-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/angle-test'>;
}
declare module 'jStat/test/linearalgebra/aug-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/aug-test'>;
}
declare module 'jStat/test/linearalgebra/cholesky-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/cholesky-test'>;
}
declare module 'jStat/test/linearalgebra/det-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/det-test'>;
}
declare module 'jStat/test/linearalgebra/divide-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/divide-test'>;
}
declare module 'jStat/test/linearalgebra/dot-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/dot-test'>;
}
declare module 'jStat/test/linearalgebra/exp-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/exp-test'>;
}
declare module 'jStat/test/linearalgebra/gauss-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/gauss-test'>;
}
declare module 'jStat/test/linearalgebra/inv-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/inv-test'>;
}
declare module 'jStat/test/linearalgebra/log-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/log-test'>;
}
declare module 'jStat/test/linearalgebra/lstsq-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/lstsq-test'>;
}
declare module 'jStat/test/linearalgebra/lu-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/lu-test'>;
}
declare module 'jStat/test/linearalgebra/multiply-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/multiply-test'>;
}
declare module 'jStat/test/linearalgebra/norm-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/norm-test'>;
}
declare module 'jStat/test/linearalgebra/outer-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/outer-test'>;
}
declare module 'jStat/test/linearalgebra/pow-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/pow-test'>;
}
declare module 'jStat/test/linearalgebra/qr-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/qr-test'>;
}
declare module 'jStat/test/linearalgebra/subtract-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/subtract-test'>;
}
declare module 'jStat/test/linearalgebra/triaLowSolve-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/triaLowSolve-test'>;
}
declare module 'jStat/test/linearalgebra/triaUpSolve-test.js' {
  declare module.exports: $Exports<'jStat/test/linearalgebra/triaUpSolve-test'>;
}
declare module 'jStat/test/models/R2-test.js' {
  declare module.exports: $Exports<'jStat/test/models/R2-test'>;
}
declare module 'jStat/test/models/simple-regression-test.js' {
  declare module.exports: $Exports<'jStat/test/models/simple-regression-test'>;
}
declare module 'jStat/test/models/thousand-size-test.js' {
  declare module.exports: $Exports<'jStat/test/models/thousand-size-test'>;
}
declare module 'jStat/test/special/gammafn-test.js' {
  declare module.exports: $Exports<'jStat/test/special/gammafn-test'>;
}
declare module 'jStat/test/special/gammap-test.js' {
  declare module.exports: $Exports<'jStat/test/special/gammap-test'>;
}
declare module 'jStat/test/special/lowRegGamma-test.js' {
  declare module.exports: $Exports<'jStat/test/special/lowRegGamma-test'>;
}
declare module 'jStat/test/template.js' {
  declare module.exports: $Exports<'jStat/test/template'>;
}
declare module 'jStat/test/test/differenceOfProportions-test.js' {
  declare module.exports: $Exports<'jStat/test/test/differenceOfProportions-test'>;
}
declare module 'jStat/test/test/qtest-test.js' {
  declare module.exports: $Exports<'jStat/test/test/qtest-test'>;
}
declare module 'jStat/test/test/ztest-test.js' {
  declare module.exports: $Exports<'jStat/test/test/ztest-test'>;
}
declare module 'jStat/test/umd/commonjs-test.js' {
  declare module.exports: $Exports<'jStat/test/umd/commonjs-test'>;
}
declare module 'jStat/test/vector/coeffvar-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/coeffvar-test'>;
}
declare module 'jStat/test/vector/corrcoeff-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/corrcoeff-test'>;
}
declare module 'jStat/test/vector/covariance-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/covariance-test'>;
}
declare module 'jStat/test/vector/cumprod-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/cumprod-test'>;
}
declare module 'jStat/test/vector/cumsum-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/cumsum-test'>;
}
declare module 'jStat/test/vector/deviation-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/deviation-test'>;
}
declare module 'jStat/test/vector/diff-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/diff-test'>;
}
declare module 'jStat/test/vector/geomean-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/geomean-test'>;
}
declare module 'jStat/test/vector/histogram-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/histogram-test'>;
}
declare module 'jStat/test/vector/kurtosis-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/kurtosis-test'>;
}
declare module 'jStat/test/vector/max-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/max-test'>;
}
declare module 'jStat/test/vector/mean-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/mean-test'>;
}
declare module 'jStat/test/vector/meandev-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/meandev-test'>;
}
declare module 'jStat/test/vector/meansqerr-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/meansqerr-test'>;
}
declare module 'jStat/test/vector/meddev-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/meddev-test'>;
}
declare module 'jStat/test/vector/median-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/median-test'>;
}
declare module 'jStat/test/vector/min-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/min-test'>;
}
declare module 'jStat/test/vector/mode-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/mode-test'>;
}
declare module 'jStat/test/vector/percentile-of-score-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/percentile-of-score-test'>;
}
declare module 'jStat/test/vector/percentile-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/percentile-test'>;
}
declare module 'jStat/test/vector/product-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/product-test'>;
}
declare module 'jStat/test/vector/quantiles-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/quantiles-test'>;
}
declare module 'jStat/test/vector/quartiles-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/quartiles-test'>;
}
declare module 'jStat/test/vector/range-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/range-test'>;
}
declare module 'jStat/test/vector/rank-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/rank-test'>;
}
declare module 'jStat/test/vector/skewness-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/skewness-test'>;
}
declare module 'jStat/test/vector/spearman-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/spearman-test'>;
}
declare module 'jStat/test/vector/stdev-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/stdev-test'>;
}
declare module 'jStat/test/vector/sum-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/sum-test'>;
}
declare module 'jStat/test/vector/sumrow-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/sumrow-test'>;
}
declare module 'jStat/test/vector/sumsqerr-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/sumsqerr-test'>;
}
declare module 'jStat/test/vector/sumsqrd-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/sumsqrd-test'>;
}
declare module 'jStat/test/vector/unique-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/unique-test'>;
}
declare module 'jStat/test/vector/variance-test.js' {
  declare module.exports: $Exports<'jStat/test/vector/variance-test'>;
}
