// flow-typed signature: 59471e7af83eb13a4dec7ffe0f27075e
// flow-typed version: <<STUB>>/redux-multi_v^0.1.12/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-multi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-multi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-multi/lib/index' {
  declare module.exports: any;
}

declare module 'redux-multi/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-multi/lib/index.js' {
  declare module.exports: $Exports<'redux-multi/lib/index'>;
}
declare module 'redux-multi/test/index.js' {
  declare module.exports: $Exports<'redux-multi/test/index'>;
}
