// flow-typed signature: ec6e25563aac13876a8945e5c1041696
// flow-typed version: <<STUB>>/scroll-into-view_v^1.9.5/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-into-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-into-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll-into-view/example/index.browser' {
  declare module.exports: any;
}

declare module 'scroll-into-view/example/index' {
  declare module.exports: any;
}

declare module 'scroll-into-view/scrollIntoView' {
  declare module.exports: any;
}

declare module 'scroll-into-view/scrollIntoView.min' {
  declare module.exports: any;
}

declare module 'scroll-into-view/standalone' {
  declare module.exports: any;
}

declare module 'scroll-into-view/test/test.browser' {
  declare module.exports: any;
}

declare module 'scroll-into-view/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll-into-view/example/index.browser.js' {
  declare module.exports: $Exports<'scroll-into-view/example/index.browser'>;
}
declare module 'scroll-into-view/example/index.js' {
  declare module.exports: $Exports<'scroll-into-view/example/index'>;
}
declare module 'scroll-into-view/scrollIntoView.js' {
  declare module.exports: $Exports<'scroll-into-view/scrollIntoView'>;
}
declare module 'scroll-into-view/scrollIntoView.min.js' {
  declare module.exports: $Exports<'scroll-into-view/scrollIntoView.min'>;
}
declare module 'scroll-into-view/standalone.js' {
  declare module.exports: $Exports<'scroll-into-view/standalone'>;
}
declare module 'scroll-into-view/test/test.browser.js' {
  declare module.exports: $Exports<'scroll-into-view/test/test.browser'>;
}
declare module 'scroll-into-view/test/test.js' {
  declare module.exports: $Exports<'scroll-into-view/test/test'>;
}
