// flow-typed signature: e4353b0bb68b079a3311df3e9146f2cc
// flow-typed version: <<STUB>>/@wordpress/babel-preset-default_v4.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@wordpress/babel-preset-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@wordpress/babel-preset-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@wordpress/babel-preset-default/index' {
  declare module.exports: $Exports<'@wordpress/babel-preset-default'>;
}
declare module '@wordpress/babel-preset-default/index.js' {
  declare module.exports: $Exports<'@wordpress/babel-preset-default'>;
}
